services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rec_radio
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network

  db:
    image: postgres:17
    container_name: morishi_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
